### ISSUE TITLE
Amazing, you've done a good job.

### ISSUE THREAD

**Issue by godofredoninja** [HauntedThemes/ghost-search#1]
It would be excellent if you modulate it for use with webpack. 

I'm updating my Ghost theme ([Simply ](https://github.com/godofredoninja/simply)and [Mapache](https://github.com/godofredoninja/Mapache)) to use this fantastic search engine. 

**This is not a mistake I just wanted to congratulate you.**  😃

**Comment by NistorCristian** [comment]
Thanks @godofredoninja . In the future I might modulate it for webpack. 👍
