### ISSUE TITLE
Why is ghost search crashing?

### ISSUE THREAD

**Issue by kash44** [HauntedThemes/ghost-search#21]
Recently the search is crashing if you input more than 10 characters in it, leaving the page unresponsive. Has anyone come across this and are there any possible solutions to this problem?

**Comment by NistorCristian** [comment]
@kash44 Interesting. We haven't got this issue. Do you have a url that you can share to take a look?

**Comment by kash44** [comment]
@NistorCristian  Yes, it is https://tryhackme.com/resources/blog

**Comment by kash44** [comment]
Hi @NistorCristian  did you manage to have a look?
