### ISSUE TITLE
Question: Separate Ghost search page

### ISSUE THREAD

**Issue by etanb** [HauntedThemes/ghost-search#4]
Hi there,

The search works well but I'm wondering if it's possible to have a results PAGE? From what I've seen so far, this gives search results inline on the page the search query was placed. What if I want to send my user to entirely new page with the search parameter in the url?

**Comment by NistorCristian** [comment]
I haven't tested but I guess it should work. You can put the search query in the url (http://example.com/search-page/?q=test). Then get that parameter with js, add the value to input, then click submit ([on button click](https://www.hauntedthemes.com/ghost-search-our-first-open-source-library-for-ghost/#get-the-results-when-a-button-is-clicked)). You can also hide with CSS the search if you don't want to be visible on the new page.

**Comment by etanb** [comment]
@NistorCristian yes I was thinking something similar where we'd pass the query to `ghost-search` if the query param appears on a specific page. The one issue is, is there a way to have `ghost-search` do its search via pure JS? IE, load results as if a user clicked the submit button without actually having them do it? 

I'd prefer not to have a hidden field that uses JS to "click" the field but rather somehow instantiate a `ghost-search` search via a JS method.

**Comment by NistorCristian** [comment]
I created a new parameter [`defaultValue`](https://github.com/HauntedThemes/ghost-search#defaultvalue) that does exactly this. Just set a value to it and it should work ok.

**Comment by etanb** [comment]
Awesome! Thanks @NistorCristian
