### ISSUE TITLE
Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by henrixvz** [HauntedThemes/ghost-search#6]
I am receiving this Error, any idea what I may be doing wrong?

![ghostsearch](https://user-images.githubusercontent.com/15246947/52744127-eeea3c80-2fc2-11e9-98bf-a226a94c674a.JPG)

**Comment by NistorCristian** [comment]
You have some [CORS ](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) issues. Your localhost url is set to http and you are trying to load the scripts from https. How do you load the scripts? Can you post the code in here?

**Comment by NistorCristian** [comment]
Closing this issue because it's not related to this library.
