### ISSUE TITLE
ghost-search on external frontends

### ISSUE THREAD

**Issue by rsarai** [HauntedThemes/ghost-search#7]
Hey folks, thanks for the lib. I was wondering if this lib works with a separated ghost frontend?

**Comment by NistorCristian** [comment]
Should work with anything. Even if you create a simple static html file on your pc ... as long as you create the integration on Ghost's dashboard and put the admin url and key in library options.

**Comment by rsarai** [comment]
Thank you! I've just made the setup on my external React app!
